[uwsgi]
processes = 2
virtualenv = /home/trrrading/trrrading/.venv/
chdir = /home/trrrading/trrrading/src/
env = DJANGO_SETTINGS_MODULE=project.settings
module = project.wsgi:application
uid = trrrading
touch-reload = /home/trrrading/trrrading/reload
socket = /home/trrrading/trrrading/uwsgi.sock
chmod-socket = 666
master=True
disable-logging=True
vacuum=True
max-requests=50000
buffer-size=65535
