# IBKR account
username: aaa
password: bbb
paper: true


# Session and Market Data Storage
redis:
  host: 127.0.0.1
  port: 6379
  db: 0
  password: null


# Session Encription Key
secret: blablabla=


instruments:
  - conid: 265598
    symbol: AAPL
    exchange: NASDAQ

  - conid: 461318791
    symbol: MES
    exchange: GLOBEX

  - conid: 211651685
    symbol: URA
    exchange: ARCA
