# Generated by Django 4.0rc1 on 2021-12-15 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='instrument',
            name='min_tick',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=5),
        ),
        migrations.AddField(
            model_name='instrument',
            name='multiplier',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='instrument',
            name='sec_type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
