# Generated by Django 4.0rc1 on 2021-12-15 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_instrument_description_instrument_min_tick_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='multiplier',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=10),
        ),
    ]
