# Generated by Django 4.2b1 on 2023-04-03 14:32

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import main.models.run


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(max_length=50, unique=True)),
                ("paper", models.BooleanField(default=False)),
                ("username", models.CharField(default="", max_length=50)),
                (
                    "net_value",
                    models.DecimalField(decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "margin_used",
                    models.DecimalField(decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "cash_value",
                    models.DecimalField(decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "ex_liq_sec",
                    models.DecimalField(decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "ex_liq_com",
                    models.DecimalField(decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "daily_pnl",
                    models.DecimalField(decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "unrealized_pnl",
                    models.DecimalField(decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "realized_pnl",
                    models.DecimalField(decimal_places=2, max_digits=12, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sid", models.CharField(default="", max_length=50)),
                (
                    "sec_type",
                    models.CharField(
                        choices=[
                            ("FUT", "Futures"),
                            ("STK", "Equity"),
                            ("OPT", "Options"),
                            ("CASH", "Cash"),
                            ("CRYPTO", "Crypto"),
                        ],
                        default="STK",
                        max_length=50,
                    ),
                ),
                (
                    "multiplier",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("1"), max_digits=10
                    ),
                ),
                (
                    "min_tick",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal(
                            "0.01000000000000000020816681711721685132943093776702880859375"
                        ),
                        max_digits=10,
                    ),
                ),
                ("price_magnifier", models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("BUY", "Buy"), ("SELL", "Sell")],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("order_id", models.PositiveIntegerField(null=True, unique=True)),
                ("local_id", models.CharField(max_length=250, null=True)),
                ("amount", models.PositiveIntegerField(default=0)),
                ("filled", models.PositiveIntegerField(default=0)),
                (
                    "type",
                    models.CharField(
                        choices=[("MKT", "Market"), ("LMT", "Limit"), ("STP", "Stop")],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "signal_price",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "limit_price",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "stop_price",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "avg_fill_price",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("is_bot", models.BooleanField(default=False)),
                ("status", models.CharField(max_length=50, null=True)),
                ("outside_rth", models.BooleanField(default=False)),
                ("order_settings", models.CharField(max_length=500, null=True)),
                ("system_comment", models.CharField(max_length=500, null=True)),
                ("string_repr", models.CharField(max_length=500, null=True)),
                ("version", models.CharField(max_length=50, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="main.account",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="main.contract"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveIntegerField(default=0)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("exec_id", models.CharField(max_length=50, null=True, unique=True)),
                ("exchange", models.CharField(max_length=50)),
                ("time", models.DateTimeField(null=True)),
                (
                    "commission",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="main.account",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades",
                        to="main.order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Run",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.CharField(
                        default=main.models.run.generate_uid, max_length=50, unique=True
                    ),
                ),
                ("backtest", models.BooleanField(default=True)),
                ("description", models.CharField(max_length=100)),
                ("broker_config", models.TextField(null=True)),
                ("strategy_config", models.TextField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("finished_at", models.DateTimeField(null=True)),
                ("from_dt", models.DateTimeField(null=True)),
                ("start_dt", models.DateTimeField(null=True)),
                ("end_dt", models.DateTimeField(null=True)),
                (
                    "account",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="main.account",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField(default=0)),
                (
                    "avg_price",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "unrealized_pnl",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="main.account"
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="main.contract"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=50, null=True)),
                ("message", models.CharField(max_length=100, null=True)),
                ("time", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.order"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="run",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="main.run",
            ),
        ),
    ]
