# Generated by Django 4.0.2 on 2022-02-09 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50, unique=True)),
                ('paper', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50)),
                ('multiplier', models.DecimalField(decimal_places=4, default=1, max_digits=10)),
                ('min_tick', models.DecimalField(decimal_places=2, default=0.01, max_digits=5)),
                ('sec_type', models.CharField(choices=[('FUT', 'Futures'), ('STK', 'Equity')], default='STK', max_length=50)),
                ('description', models.CharField(default='', max_length=100)),
                ('conid', models.PositiveIntegerField(null=True)),
                ('main_exchange', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.exchange')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=50, null=True)),
                ('order_id', models.PositiveIntegerField(null=True, unique=True)),
                ('local_id', models.CharField(max_length=50, null=True)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('filled', models.PositiveIntegerField(default=0)),
                ('type', models.CharField(choices=[('MKT', 'Market'), ('LMT', 'Limit')], max_length=50, null=True)),
                ('signal_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('limit_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('avg_fill_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('is_bot', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=50, null=True)),
                ('version', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.account')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.instrument')),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('exec_id', models.CharField(max_length=50, null=True, unique=True)),
                ('exchange', models.CharField(max_length=50)),
                ('time', models.DateTimeField(null=True)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='main.order')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.account')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.instrument')),
            ],
        ),
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, null=True)),
                ('message', models.CharField(max_length=100, null=True)),
                ('time', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.order')),
            ],
        ),
    ]
