# Generated by Django 4.2 on 2023-04-12 22:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="is_bot",
        ),
        migrations.AddField(
            model_name="order",
            name="algo_params",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="algo_strategy",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="oca_group",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="raw",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="tif",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="trailing_amount",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="trailing_percent",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="type",
            field=models.CharField(
                choices=[
                    ("MKT", "Market"),
                    ("LMT", "Limit"),
                    ("STP", "Stop"),
                    ("STP LMT", "Stop Limit"),
                    ("TRAIL", "Trail"),
                    ("TRAIL LIMIT", "Trail Limit"),
                    ("MIDPRICE", "MidPrice"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
