# Generated by Django 4.0.2 on 2022-02-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='outside_rth',
            field=models.BooleanField(default=False),
        ),
    ]
