# Generated by Django 4.2 on 2023-04-13 22:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_remove_order_is_bot_order_algo_params_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="avg_price",
            field=models.DecimalField(decimal_places=5, max_digits=12, null=True),
        ),
    ]
