# Generated by Django 4.0.2 on 2022-02-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_order_outside_rth'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='avg_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='unrealized_pnl',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
