# Generated by Django 4.2 on 2023-04-24 22:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_position_avg_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_id",
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
