# Generated by Django 4.0.2 on 2022-02-25 23:33

from django.db import migrations, models
import django.db.models.deletion
import main.models.run


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_position_avg_price_position_unrealized_pnl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=main.models.run.generate_uid, max_length=50, unique=True)),
                ('backtest', models.BooleanField(default=True)),
                ('description', models.CharField(max_length=100)),
                ('broker_config', models.TextField(null=True)),
                ('strategy_config', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('from_dt', models.DateTimeField(null=True)),
                ('start_dt', models.DateTimeField(null=True)),
                ('end_dt', models.DateTimeField(null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.account')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='run',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.run'),
        ),
    ]
