# Generated by Django 4.2 on 2023-04-26 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_alter_order_order_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderevent",
            name="code",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="orderevent",
            name="message",
            field=models.TextField(null=True),
        ),
    ]
