# Generated by Django 4.2 on 2023-04-26 22:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_orderevent_code_alter_orderevent_message"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="username",
        ),
        migrations.RemoveField(
            model_name="order",
            name="string_repr",
        ),
        migrations.RemoveField(
            model_name="order",
            name="system_comment",
        ),
        migrations.RemoveField(
            model_name="order",
            name="version",
        ),
        migrations.AlterField(
            model_name="account",
            name="cash_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="daily_pnl",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="ex_liq_com",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="ex_liq_sec",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="margin_used",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="net_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="realized_pnl",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="unrealized_pnl",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="sid",
            field=models.CharField(db_index=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="order",
            name="algo_params",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="algo_strategy",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="local_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=250, null=True
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="oca_group",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_id",
            field=models.IntegerField(
                blank=True, db_index=True, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_settings",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="raw",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="tif",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="orderevent",
            name="code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="orderevent",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="orderevent",
            name="status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="orderevent",
            name="time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="position",
            name="avg_price",
            field=models.DecimalField(
                blank=True, decimal_places=5, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="unrealized_pnl",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
