# Generated by Django 4.0.2 on 2022-03-01 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_account_description_account_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.account'),
        ),
    ]
