# Generated by Django 4.2 on 2023-05-08 01:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_blank_true"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="avg_fill_price",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="limit_price",
            field=models.DecimalField(decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="signal_price",
            field=models.DecimalField(decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="stop_price",
            field=models.DecimalField(decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="trailing_amount",
            field=models.DecimalField(decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="trailing_percent",
            field=models.DecimalField(decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name="trade",
            name="commission",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name="trade",
            name="price",
            field=models.DecimalField(decimal_places=6, default=0, max_digits=15),
        ),
    ]
