# Generated by Django 4.0.2 on 2022-03-24 03:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cash_value',
            field=models.DecimalField(decimal_places=5, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='ex_liq_com',
            field=models.DecimalField(decimal_places=5, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='ex_liq_sec',
            field=models.DecimalField(decimal_places=5, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='margin_used',
            field=models.DecimalField(decimal_places=5, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='net_value',
            field=models.DecimalField(decimal_places=5, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
