# Generated by Django 4.0.3 on 2022-07-15 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_account_cash_value_account_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_settings',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='string_repr',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='system_comment',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
