# Generated by Django 4.2b1 on 2023-02-26 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0010_order_order_settings_order_string_repr_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instrument",
            name="description",
        ),
        migrations.AddField(
            model_name="instrument",
            name="local_symbol",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="trade",
            name="account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="main.account",
            ),
        ),
    ]
