# Generated by Django 4.2b1 on 2023-02-26 21:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0011_remove_instrument_description_and_more"),
    ]

    operations = [
        migrations.RenameModel('Instrument', 'Contract')
    ]