# Generated by Django 4.2b1 on 2023-02-26 22:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0012_auto_20230226_1356"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="instrument",
            new_name="contract",
        ),
        migrations.RenameField(
            model_name="position",
            old_name="instrument",
            new_name="contract",
        ),
    ]
