# Generated by Django 4.2b1 on 2023-02-28 23:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0013_rename_instrument_order_contract_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="min_tick",
            field=models.DecimalField(decimal_places=4, default=0.01, max_digits=8),
        ),
        migrations.AlterField(
            model_name="contract",
            name="sec_type",
            field=models.CharField(
                choices=[
                    ("FUT", "Futures"),
                    ("STK", "Equity"),
                    ("OPT", "Options"),
                    ("CASH", "Cash"),
                ],
                default="STK",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="local_id",
            field=models.CharField(max_length=250, null=True),
        ),
    ]
