# Generated by Django 4.2b1 on 2023-03-01 03:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0014_alter_contract_min_tick_alter_contract_sec_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="daily_pnl",
            field=models.DecimalField(decimal_places=5, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="realized_pnl",
            field=models.DecimalField(decimal_places=5, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="unrealized_pnl",
            field=models.DecimalField(decimal_places=5, max_digits=12, null=True),
        ),
    ]
