# Generated by Django 4.2b1 on 2023-03-01 04:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0015_account_daily_pnl_account_realized_pnl_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="cash_value",
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="daily_pnl",
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="ex_liq_com",
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="ex_liq_sec",
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="margin_used",
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="net_value",
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="realized_pnl",
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="unrealized_pnl",
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
