# Generated by Django 4.2b1 on 2023-03-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0016_alter_account_cash_value_alter_account_daily_pnl_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="stop_price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="type",
            field=models.CharField(
                choices=[("MKT", "Market"), ("LMT", "Limit"), ("STP", "Stop")],
                max_length=50,
                null=True,
            ),
        ),
    ]
