# Generated by Django 4.2b1 on 2023-03-21 00:01

from django.db import migrations, models


def set_sid_value(apps, schema_editor):
    from main.models import Contract
    for obj in Contract.objects.all():
        obj.sid = obj.psid()
        obj.save()


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0017_order_stop_price_alter_order_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="sid",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.RunPython(set_sid_value),
        migrations.AlterField(
            model_name="contract",
            name="sec_type",
            field=models.CharField(
                choices=[
                    ("FUT", "Futures"),
                    ("STK", "Equity"),
                    ("OPT", "Options"),
                    ("CASH", "Cash"),
                    ("CRYPTO", "Crypto"),
                ],
                default="STK",
                max_length=50,
            ),
        ),
    ]
