# Generated by Django 4.2b1 on 2023-03-21 00:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0018_contract_sid_alter_contract_sec_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contract",
            name="conid",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="local_symbol",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="main_exchange",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="symbol",
        ),
    ]
