# Generated by Django 4.2b1 on 2023-03-21 03:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0019_remove_contract_conid_remove_contract_local_symbol_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Exchange",
        ),
    ]
