# Generated by Django 4.2b1 on 2023-03-22 02:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0020_delete_exchange"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="price_magnifier",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="contract",
            name="min_tick",
            field=models.DecimalField(
                decimal_places=6,
                default=Decimal(
                    "0.01000000000000000020816681711721685132943093776702880859375"
                ),
                max_digits=10,
            ),
        ),
    ]
